server:
  port: 9000
  servlet:
    context-path: /demo_elasticsearch
spring:
  name: demo-elasticsearch
  profiles:
    active: dev
  redis:
    host: 10.202.16.136
    port: 6379

##是否启动本地redis
redis:
  local:
    active: false
    maxheap: 200m
    port: 6379